[package]
name = "proto-handler"
version = "0.1.0"
authors = ["Maxwell Borden <maxwellborden@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
